godotengine/build-containers

Dockerfile.base

Note: I branched off the current `master` branch to 3.1, so that we can keep the same containers for 3.1.x and upgrade them for 3.2/master.

base: Use Fedora 30 for godot-fedora:latest

---

Dockerfile.javascript

This way we shouldn't need to source `emsdk_env.sh` manually when building templates.

javascript: Cleanup and source env in ~/.bashrc

---

Dockerfile.mono
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows

This should actually be merged before #3 and #4 which build upon this image.
Mono 6.0.x now ships as `.tar.xz` so some changes were needed. It also seems to have a bogus `configure` by default, so we fix it with `autoreconf -vfi`.
I also bumped all msbuild packages to their latest version from `centos8-stable`.

mono: Add support for mono 6.0.x

---

Dockerfile.android
build.sh
files/patches/fix-mono-android-tkill.diff

Adds support for building Mono templates for Android in 3.2/master.
Expects mono 6.0+ (otherwise we'd have to handle the tarball compression
change from upstream).
We use the script from https://github.com/godotengine/godot-mono-builds
to build Mono for all arches with the right options, and a patch included
in https://github.com/godotengine/godot/blob/master/modules/mono/build_scripts/patches/fix-mono-android-tkill.diff
which is also necessary.
I also moved the SDK to a `sdk` folder to make the `$HOME` more tidy,
especially since the Mono build scripts install the mono toolchains in
`$HOME` too by default.

android: Set up Mono buildsystem

---

Dockerfile.javascript

Docker.javascript fails to build
```
Cloning into 'emsdk'...
remote: Enumerating objects: 25, done.        
remote: Counting objects: 100% (25/25), done.        
remote: Compressing objects: 100% (21/21), done.        
remote: Total 1694 (delta 11), reused 7 (delta 4), pack-reused 1669        
Receiving objects: 100% (1694/1694), 960.21 KiB | 492.00 KiB/s, done.
Resolving deltas: 100% (1068/1068), done.
./emsdk: line 18: exec: python: not found
```
This docker installs scons which pulls in python3. There is no `python` command.
How do you want to handle it? Especially regarding #13. 
* Add `python` to the list of requested packages (which pulls in python2 [2.7.17])?
* `ln -s python3 python`?
Also, due to this emsdk bug, 
https://github.com/godotengine/godot/issues/33374 
shouldn't we …

Fix Docker.javascript not building

---

Dockerfile.android
Dockerfile.base
Dockerfile.export
Dockerfile.ios
Dockerfile.javascript
Dockerfile.mono
Dockerfile.mono-glue
Dockerfile.msvc
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows
Dockerfile.xcode

Since we need to install those deps in most leaf containers, I figure it might be better to simply get them in the base one.
We can discuss whether all those should be included in the base or if some should be left in leaf containers, as well as whether we want to include more stuff in the base container (perl? nano? :P).
We also have a couple containers installing `python`, but I'm not sure it's really needed. We should likely aim for being python3-only (see also #13).

Install common dependencies in Dockerfile.base

---

Dockerfile.android
Dockerfile.mono
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows

The main reason is that upstream Mono tends to miss some
important files in its tarballs, so Git tags appears to be
a more reliable medium.
Also split RUN further to do cleanup in a separate stage,
allowing to inspect intermediary images to debug build or
packaging issues.
---
**Depends on #16.**
Includes commits from #16, I'll rebase once that first PR is merged.
Only the last commit in this PR is meant to be reviewed here.

Use git tag to checkout stable mono releases

---

.gitignore
Dockerfile.android
Dockerfile.export
Dockerfile.ios
Dockerfile.javascript
Dockerfile.mono
Dockerfile.mono-glue
Dockerfile.msvc
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows
Dockerfile.xcode
build.sh

The previous `['/bin/bash']` was not working, running the image
with `podman run -it <name>` would evaluate to:
```
> sh -c ['/bin/bash']
sh: [/bin/bash]: No such file or directory
```

Use /bin/bash as default CMD, log container build output

---

Dockerfile.osx
Dockerfile.xcode

The osxcross installation process has been improved and now supports
more recent versions of Xcode than 7, so most of our custom code is
no longer needed.
The xcode packer could also be reworked to use osxcross' SDK packing
script.
Fixes #15.

OSX: Fix support for latest osxcross and Xcode 10.13

---

Dockerfile.android
Dockerfile.javascript
Dockerfile.mono
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows
files/patches/mono-wasm-avoid-aligning-stack-bounds.patch

To get WebAssembly templates to actually work, we need to use
Mono 6.6 (currently in preview), which doesn't have tags yet
but is in the `2019-08` branch. So I dehardcoded the `mono-`
prefix for the git tree-ish to allow using `./build.sh 2019-08`.
6.6 doesn't build with msbuild 16.0, so I'm upgrading to its
matching version 16.3. There are no DEB files for 16.3 on the
EOL'ed Ubuntu 14.04, but it seems that the 16.04 packages install
cleanly.
We also backport a patch from mono's master branch to fix wasm
support further, and enable parallel build jobs for make.

mono: Update msbuild to 16.3, support for git branches

---

build.sh

E.g. `3.1-mono-5.18.1.3` or `master-2019-08`.
The images which do not include mono only use the Godot branch,
i.e. `3.1` or `master`.

Refactor image versioning, using $godot_branch-$mono_version format

---

Dockerfile.osx
files/mono-config-macosx

This effectively means that we can't use the current Dockerfile.osx
to build mono < 6.0, as the DLL path changed.
I've asked users on Discord to confirm that this fixes the issue, will merge if they do.
Related issue (for Windows): godotengine/godot#33822.

OSX: Fix config file for mono 6.0+

---

Dockerfile.android
Dockerfile.javascript
Dockerfile.mono
Dockerfile.mono-glue
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows
build.sh

Specifying only a branch like '2019-08' is problematic if upstream commits
something between the builds of two containers.
We could make a tarball in the first container build and reuse that, but we
need the flexibility of Git for some patching in the Android and JavaScript
builds, so instead we allow specifying a git tree-ish as the third argument.
We can therefore also give a pretty version string to use for the image name
as second argument, e.g. 6.6.0.160 for bef1e6335812d32f8eab648c0228fc624b9f8357.
As we can't `git clone` a commit hash directly, we still need to provide both
branch name and then commit hash for this use case.
Follow up to #23.

Mono: Allow specifying fixed git hash and pretty image version

---

files/mono-config-macosx

Taken from a system-wide install of Mono 6.4 on macOS,
provided by @neikeq.

OSX: Update Mono config based on upstream one

---

Dockerfile.windows
build.sh
files/mono-build-win32.sh
files/patches/wine-mono.patch

This can be reverted once a proper fix has been deployed in upstream
Mono. No ETA yet as we're busy and it's unlikely to happen if we don't
do it ourselves :)
Co-authored-by: @hpvb
---
I made it all one `RUN` step and removed `wine` in the end, so we should hopefully end up with a leaner container. It's just temporary until @hpvb has time to work on using proper build steps to improve the overall workflow.

Windows: Workaround Mono 6 BCL cross-compiling bug using Wine

---

Dockerfile.android
Dockerfile.javascript
Dockerfile.windows

Like most programming language, in a logic statement `A && B || C`,
bash will not evaluate B if A is false (failing in our case).
Using `A && (B || C)` to prevent that.
A build error in the Windows 32-bit Mono build thus caused skipping
all subsequent `ln` statements up until `|| /bin/true`, which is used
to link only the folders which are missing from the self-built mono
prefix.
The build error still needs to be fixed but it doesn't seem to prevent
using the resulting container to build 32-bit Windows binaries.
---
The other commit is a updating the Android and JS containers to the latest commit on https://github.com/godotengine/godot-mono-builds, which reduces the size of their BCL somewhat and should make templates leaner.

Windows: Prevent 32-bit build failure from skipping symlinks

---

Dockerfile.windows
files/mono-build-win32.sh

Symlinking the BCL from `/usr/lib/mono` no longer seems needed
for either architecture, everything is built properly.
Fixes #34.
----
This seemed to work in-container when doing a test. I'm now making a full rebuild of the container and will do a test Mono win64 and win32 build off the `master` branch to confirm that everything works as intended.

Windows: Set WINEPATH for 32-bit wine to fix Mono build

---

Dockerfile.android
Dockerfile.javascript
Dockerfile.mono
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows
build.sh
files/patches/mono-unity-Clear-TLS-instead-of-aborting.patch

Fixes godotengine/godot#33735.
---
I already rebuilt all containers successfully with this patch.
I'll make a test build for desktop platforms to confirm that it fixes the issue.

Mono: Add patch from Unity fork to fix TLS re-attachment

---

Dockerfile.android
Dockerfile.base
Dockerfile.export
Dockerfile.ios
Dockerfile.javascript
Dockerfile.mono
Dockerfile.mono-glue
Dockerfile.msvc
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.windows
Dockerfile.xcode
build.sh

* Moves mono downloads from dockers to build.sh
* Retains dnf cache
* Adds progress to git downloads
* Replaces `git apply` with more reliable `patch`
Should address relevant notes in reference #38 
Note: `dnf clean all` became `dnf clean packages` to save dnf cache and only remove the packages. However the [default dnf configuration](https://dnf.readthedocs.io/en/latest/conf_ref.html) doesn't save the packages. keepcache=false is the default and must be set true in `/etc/dnf/dnf.con` in order to save packages. So `dnf clean` is removed entirely everywhere.

Optimize mono & dnf downloads

---

Dockerfile.ubuntu-32
Dockerfile.ubuntu-64

This merges against master.
I just built godot with both 32 and 64 bit dockers after this. There are few changed dependencies upon installing gcc 9. glibc is still 2.19.
Should not conflict with #40, but it will with #41 .

Move Ubuntu to gcc 9.2.1

---

Dockerfile.javascript
files/patches/mono-pr17094-bump-emscripten-1.38.46.patch

As a reminder, we pinned the Emscripten version to `1.38.47-upstream` as we had a regression with wasm generation in 1.38.48 and 1.39.x back in 17666f07fe.
This patch comes from Mono's `2019-10` branch (6.8.x): https://github.com/mono/mono/pull/17094
(Slightly amended to include a version bump in `wasm.mk` that should have been done by other intermediate patches.)
We might need a recent Emscripten 1.39.x in the `3.2` branch eventually (CC @Faless), so we might have to consider upgrading to a newer Mono branch with support for a more recent Emscripten.

Wasm: Fix mono patch application on Emscripten 1.38.47

---

.gitignore
Dockerfile.android
Dockerfile.javascript
build.sh

This will also be used for iOS so it makes sense to do it all
together with the split out mono clone.
This also allows to pin the commit used more easily.
---
Yet untested, I'll do a follow up PR with iOS buildsystem changes for C# support and will use it to validate this first commit.

Factor out cloning and patching for godot-mono-builds

---

Dockerfile.android
Dockerfile.javascript
build.sh
files/mono-build-win32.sh

Builds are faster with 64 jobs instead of 1 :)
It's mostly relevant for 'make' but we also use the -j flag
for 'configure' as it can also trigger a build for external
dependencies (like llvm for upcoming iOS Mono builds).
--
The previous `export make="make -j"` trick was not functional.

Use parallel make in godot-mono-builds scripts

---

Dockerfile.ios
build.sh

WIP build of the iOS Mono components to use in 3.2.x and master.
The separate `RUN` commands are to allow debugging intermediate stages until I'm confident that everything builds fine and as wanted.
The `PATH` and `LD_LIBRARY_PATH` changes are also local hacks that should be done directly by the godot-mono-builds scripts, since we provide `OSXCROSS_ROOT` and `--ios-toolchain` already to allow computing them.
----
Currently the last step is failing (building the cross-compiler) as the relevant godot-mono-builds script doesn't support osxcross fully yet.
One issue is that it fails detecting osxcross due to a typo, which is easily fixed:
```diff
diff --git a/ios.py b/ios.py
index 5a4e991..cec86aa 100755
--- a/ios.py
+++ b/ios.py
@@ -339,7 +339,7 @@ def setup_ios_cross_template(env: dict, …
```

iOS: Build Mono runtime

---

Dockerfile.ios
Dockerfile.osx
Dockerfile.xcode
build.sh
files/patches/mono-sys-uio-fix-preadv-misdetection.patch
files/patches/mono-xcode-allow-weak-import.patch

Provides SDKs for iOS 14.0 and macOS 10.15.
Mono is patched to fix a regression in Xcode 11.4+, still unfixed by Apple.
Fixes missing arguments in Xcode and iOS dockerfiles, seems like some changes
were not properly committed during the last refactor.
----
WIP as I'm still running into issues building Mono for iOS:
```
/root/mono-6.6.0.166/support/sys-uio.c:99:8: error: implicit declaration of function 'preadv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
res = preadv (dirfd, v, iovcnt, (off_t) off);
^
/root/mono-6.6.0.166/support/sys-uio.c:119:8: error: implicit declaration of function 'pwritev' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
res = pwritev (dirfd, v, iovcnt, (off_t) off);
^
2 errors generated.
```

iOS and OSX: Upgrade containers to use latest osxcross and Xcode 12.0.1

---

Dockerfile.ios
Dockerfile.osx
Dockerfile.xcode
build.sh

- macOS 11.0 SDK for Big Sur update
- iOS 14.2 SDK
Cf. https://github.com/godotengine/godot-build-scripts/pull/10
---
Still missing is actually building Mono for arm64.

Update to Xcode 12.2 SDKs

---

Dockerfile.android
build.sh

The fix is done in https://github.com/godotengine/godot-mono-builds/pull/22.
Also bump build-tools/platform to API 30 to match current 3.2 branch.

Android: Fix 32-bit Mono builds compat with API < 21

---

Dockerfile.javascript

Mono 6.12 still forces us to stick to 1.39.9, so there won't be GDNative support
for it initially. But we can install 2.0.10 for standard builds.
The activation of the relevant toolchain will be done in the build scripts.

JavaScript: Install Emscripten 2.0.10 for standard builds with GDNative

---

Dockerfile.android

Update configuration based on the Android buildsystem change in https://github.com/godotengine/godot/pull/44949.

Android: Update env variables and NDK preinstallation to match Godot buildsystem changes

---

Dockerfile.ios

That release matches Mono 6.12.0.114.
Fixes #67.

iOS: Download arm64 AOT compiler directly from godot-mono-builds

---

Dockerfile.base
Dockerfile.ios
Dockerfile.javascript
Dockerfile.mono
Dockerfile.osx
Dockerfile.ubuntu-32
Dockerfile.ubuntu-64
Dockerfile.xcode
README.md
build.sh
upload.sh

FYI @Faless @neikeq @bruvzg @naithar 
That's what I plan to use for 3.3 RC7 / stable.
Tested to make a local `3.x-mono-6.12.0.122` build, will upload it to @hpvb's registry soon.
I also made a successful build of Godot from the `3.x` branch for all platforms, standard + Mono.

Update images to Fedora 33, Mono 6.12.0.122, Xcode 12.4, Emscripten 2.0.15

---

Dockerfile.ubuntu-32

We've had troubles trying to upgrade GCC on Ubuntu 14.04 i386 containers
as statically linking libstdc++ would then trigger crashes when running
those binaries on more recent Ubuntu versions (which seems to be a Ubuntu
bug, other distros don't have the problem).
Upgrading to Ubuntu 16.04 and using its default GCC 5 version seems to
produce working binaries even with statically linked libstdc++, and that
should still be good enough for the few 32-bit Linux users we have.
Ref. https://github.com/godotengine/godot/issues/31743

Linux 32-bit x86: Update container to Ubuntu 16.04, keep GCC 5

---

Dockerfile.ios

Adds ARM64 iOS simulator toolchain and Mono builds.
Depends on https://github.com/godotengine/godot-mono-builds/pull/30

Add Apple Silicon iOS simulator build support.

---

Dockerfile.ios

We have to wait for a resolution to https://github.com/tpoechtrager/cctools-port/issues/102
or try a custom LLVM build with the proposed patch in that issue.
Matching scripts update: https://github.com/godotengine/godot-build-scripts/pull/41

iOS: Disable non-working arm64 simulator build

---

Dockerfile.windows
build.sh

Includes https://github.com/godotengine/godot-mono-builds/pull/46, will rebase to point to the merge commit once merged.

Windows: Update godot-mono-builds with fixed copy_bcl for win32

---

Dockerfile.osx

Includes backport of https://github.com/tpoechtrager/osxcross/pull/286.

macOS: Build compiler_rt for ARM64 too

---

Dockerfile.xcode

It's better maintained than https://github.com/mackyle/xar and that saves us
some work.
Supersedes #88 and #89.
---
Note: Still testing that the generated SDK tarballs can be used to build the macOS and iOS containers properly.
*Edit:* I could build osxcross and ioscross without issue so it seems like the extracted SDKs are valid.

Xcode: Install `xar` package from Fedora

---

Dockerfile.linux

So we can build for Raspberry PI 3/4 (armv8-a) :pie: .
I will open a PR in the build-scripts repository soon :)

[Linux] Add armhf toolchain to the build image.

---

Dockerfile.base
Dockerfile.export
Dockerfile.ios
Dockerfile.javascript
Dockerfile.mono-glue
Dockerfile.osx
build.sh

- F36 gives us MinGW GCC 11.2.1 and binutils 2.37 for Windows builds.
* Had to downgrade autotools to F35 version for Mono wasm builds.
- OSX and iOS builds now use LLVM 14 for osxcross.
- Emscripten updated to 3.1.10 for classical builds (still using
1.39.9 for Mono).
- Mono 6.12.0.178, and updated godot-mono-builds to fix issue with
btls-lib on macOS ARM64 (fixes https://github.com/godotengine/build-containers/issues/95).
- SCons 4.3.0.
- ~Add `osslsigncode` to Linux image for use in godot-build-scripts.~ *Edit:* Removed, I ended up not using it in https://github.com/godotengine/godot-build-scripts/pull/53
- Linux toolchains not updated yet, need to prepare a new buildroot
with latest GCC/binutils.
Syncs with latest godot-mono-builds: …

Upgrade to Fedora 36 and Mono 6.12.0.178, newer toolchains

---

Dockerfile.base
Dockerfile.javascript

Notably LLVM 14 on F36 doesn't seem to play nice with macOS builds.
We probably need to wait for Xcode 14 to have support for LLVM 14.
Going back to F35 also avoids issues with autoconf 2.71.

Set base to Fedora 35 for now, F36 still a bit too new

---

Dockerfile.base
Dockerfile.javascript
Dockerfile.osx

This reverts #105 as we found that the MinGW/GCC/binutils
combinations in Fedora 35 generates broken Windows binaries:
https://github.com/godotengine/godot/issues/61176
To workaround the issue with LLVM 14 on F36, we build Clang 13.0.1
from source for osxcross in the OSX container. This matches Xcode 13.

Set base to Fedora 36, F35 had worse issues

---

Dockerfile.android
Dockerfile.base
Dockerfile.ios
Dockerfile.javascript
Dockerfile.osx
build.sh

Keeping NDK r21 for building Mono itself as it's not compatible yet
with NDK r22+ (see https://github.com/godotengine/godot-mono-builds/issues/68).

Update to Android NDK r23, Emscripten 3.1.14

---

Dockerfile.web
README.md

Emscripten 3.1.19 and 3.1.20 have a showstopping regression that breaks calling our main function for the editor build.

Web: Downgrade to Emscripten 3.1.18

---

Dockerfile.ios
Dockerfile.osx
Dockerfile.xcode
build.sh

Use Fedora 36's Clang since it provides version 14.0.5 which fits the version used by Xcode 14.1.

Xcode: Update to Xcode 14.1, macOS 13.0, iOS 16.1

---

Dockerfile.ios
build.sh

Namely the fix for https://github.com/godotengine/godot-mono-builds/issues/79.

macOS: Update godot-mono-builds to fix missing ARM64 btls lib

---

build.sh

Instead of requiring the script to be executed from the root of the repo due to `$(pwd)/files` and `files/`, use `$(dirname "$0"; pwd)/files` and `$files_root`.

Support executing `build.sh` from anywhere

---

build.sh

Skip confirmation if the build script is run in a non-interactive shell (for instance, in CI).

build: skip confirm if non-interactive

---

build.sh
setup.sh
upload.sh

On my NixOS machine, there is no "/bin/bash". my bash executable located at "/run/current-system/sw/bin/bash", so ./build ends with error. To avoid that, I changed "/bin/bash" to "/usr/bin/env bash". As far as I know, "/usr/bin/env" exists on every major distro, and basically returns path to shell, in our case it's bash. With this change, script will run on any distro, it doesn't matter where bash executable is located.

Change "/bin/bash" to "/usr/bin/env bash" in shell files

---

Dockerfile.android
Dockerfile.base
Dockerfile.ios
Dockerfile.osx
Dockerfile.web
Dockerfile.xcode
README.md
build.sh

Update to Fedora 39, update all toolchains
- Base image: Fedora 39
- SCons: 4.5.2
- Linux: GCC 10.2.0 built against glibc 2.19, binutils 2.35.1
- Windows: MinGW 11.0.0, GCC 13.2.1, binutils 2.40
- Web: Emscripten 3.1.39
- Android: Android NDK 23.2.8568313, build-tools 33.0.2, platform android-33, CMake 3.22.1, JDK 17
- macOS: Xcode 15.0 with Apple Clang (LLVM 16.0.0), MacOSX SDK 14.0
- iOS: Xcode 15.0 with Apple Clang (LLVM 16.0.0), iPhoneOS SDK 17.0
Switches macOS/iOS builds to use Apple Clang, to maximize compatibility with upstream Xcode. ~This enables us to build the arm64 simulator for iOS.~ (Still doesn't work.)
Also add gettext which is needed by Godot build scripts to compile PO files to MO.
---
Draft for now as I haven't tested building Godot with those yet. I expect at least for …

Update to Fedora 39, update all toolchains

---

Dockerfile.linux
README.md

Provides GCC 13.2.0 built against glibc 2.28, binutils 2.40.

Linux: Update buildroot SDK to 2023.08, add arm64 SDK

---

Dockerfile.linux

The only change is https://github.com/godotengine/buildroot/commit/e6c2704eb22f0ea2a5dbe3d3084cec414ae540c8:
> Build with 16K page sizes in mind on aarch64
>
> By default binutils on buildroot aligns sections to 4kb boundaries, but
> there are several 16k only linux distros out there now that default to
> 16kb pages.
>
> With this change the elf files will have their sections aligned to 16kb
> boundaries which should ensure binaries produced with the toolchain work
> on most aarch64 linuxes.

Update Linux SDK to 2023-12-11 release, fixes arm64 Rasperry Pi compatibility

---

Dockerfile.android
Dockerfile.base
Dockerfile.ios
Dockerfile.javascript
Dockerfile.linux
Dockerfile.mono
Dockerfile.osx
Dockerfile.windows
Dockerfile.xcode
README.md
build.sh
setup.sh
upload.sh

Syncs with the config of the current `main` branch (as used for 4.2+) as far as possible (backports the last couple of years of PRs, minus the removal of some platforms and of the Mono builds).
Notably backports #128 and #131, giving us these toolchains:
- Base image: Fedora 39
- Mono version: 6.12.0.198
- SCons: 4.5.2
- Linux: GCC 13.2.0 built against glibc 2.28, binutils 2.40, from our own [Linux SDK](https://github.com/godotengine/buildroot)
- Windows: MinGW 11.0.0, GCC 13.2.1, binutils 2.40
- HTML5: Emscripten 3.1.39 (standard builds), Emscripten 1.39.9 (Mono builds)
- Android: Android NDK 23.2.8568313, build-tools 33.0.2, platform android-33, CMake 3.22.1, JDK 11
- macOS: Xcode 15.0 with Apple Clang (LLVM 16.0.0), MacOSX SDK 14.0
- iOS: Xcode 15.0 with Apple Clang (LLVM 16.0.0), …

[3.x] Update to Fedora 39, newer toolchains, add Linux arm64

---

Dockerfile.linux

Includes https://github.com/godotengine/buildroot/pull/11.

Update Linux SDK to 2024-01-17 release, fixes arm32 lacking NEON

---

Dockerfile.linux

Same as https://github.com/godotengine/build-containers/pull/136.

[3.x] Update Linux SDK to 2024-01-17 release, fixes arm32 lacking NEON

---

Dockerfile.ios
Dockerfile.linux
Dockerfile.osx
Dockerfile.web
README.md
build.sh

- .NET 8.0
- SCons 4.6.0
- Xcode 15.2 (macOS 14.2, iOS 17.2)
- Android API 34
- Emscripten 3.1.53
- Add wayland-devel dependency for Linux
---
Note: I used an intermediate version of this patch for the 4.3-dev3 release, without the OSX and iOS changes.

Update various toolchains for 4.3

---

Dockerfile.web

Backporting https://github.com/emscripten-core/emscripten/pull/19496 while we wait for 3.1.62.

Web: Patch Emscripten 3.1.61 to include PR 19496, fixing threads+dlink build

---

Dockerfile.windows

Adds commands to download and extract [MinGW/LLVM](https://github.com/mstorsjo/llvm-mingw) toolchain. Toolchain is installed in `/root/llvm-mingw`.

Add pre-built MinGW/LLVM toolchain to the Windows build container to support ARM64 Windows builds.
